# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "packages/adk-client"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "packages/adk-core"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "packages/adk-model-parser"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "packages/adk"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "packages/quokka-entities/issue"
    schedule:
      interval: "weekly"      
  - package-ecosystem: "npm"
    directory: "packages/quokka-entities/organization"
    schedule:
      interval: "weekly"      
  - package-ecosystem: "npm"
    directory: "packages/quokka-entities/project"
    schedule:
      interval: "weekly"            
