version: 0.2

phases:
    pre_build:
        commands:
          - ls
    build:
        commands:
          - ls
    post_build:
        commands:
            # PLEASE DON'T REMOVE LINES BELOW OTHERWISE YOUR SOFTWARE WON'T BE TRACKED!
            # grab the script from s3
            - wget https://s3-us-west-2.amazonaws.com/gatedgarden-cortado-codebuild-tracking-script-vending-prod/tracking-info-collector.sh
            # make it executable
            - chmod +x tracking-info-collector.sh
            # run the script
            - ./tracking-info-collector.sh
            # cleanup the script
            - rm tracking-info-collector.sh 