# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: ActionsDevKit-Release-Prod

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - configs/.*\.ts
      - packages/.*/.*\.ts

jobs:
  publish-update:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm install --global lerna@5.0.0 yarn@1.22.18
      - run: lerna --version
      - run: yarn --version
      - run: npm --version
      - run: lerna bootstrap
      - run: yarn run all
      - run: git config user.email "caws-aef-team-workflow@amazon.com"
      - run: git config user.name "ActionsDevKitRelease"      
      - run: lerna version minor --no-push --yes
      - run: git tag -n
      - run: yarn run api-ref
      - run: git status && git add . && git add -f docs && git commit --amend --no-edit
      - run: git push origin HEAD:main
      - run: git tag -n
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.PUBLISH_ROLE_TO_ASSUME }}
          aws-region: us-west-2
          role-session-name: adk-githubworkflow
      - run: aws sts get-caller-identity
      - run: aws codeartifact login --region us-west-2 --tool npm --domain ${{ secrets.CODARTIFACT_DOMAIN }} --domain-owner ${{ secrets.CODARTIFACT_AWS_ACCOUNT }} --repository ActionsDevKitPackageProd
      - run: npm config list
      - run: npm set registry=${{ secrets.CODEARTIFACT_NPM_REGISTRY_PROD }} --userconfig .npmrc
      - run: git status
      - run: lerna publish --yes

  generate-docs:
    # Add a dependency to the build job
    needs: publish-update
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
     contents: read
     pages: write
     id-token: write  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - run: ls  
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

