# This workflow will build and run tests using node and then publish a package to the public NPM repository
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: adk-unpublish-version

on: [workflow_dispatch]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  GIT_COMMITTER_NAME: ActionsDevKitRelease
  GIT_COMMITTER_EMAIL: cawsactionextensions+adk-release@amazon.com

jobs:
  unpublish-from-npm:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org/'
          scope: '@aws'
      # Install dependencies
      - run: npm install --global lerna@5.0.0 yarn@1.22.18
      - run: lerna --version
      - run: yarn --version
      - run: npm --version

      # Un-Publishes ADK package from NPM (order matters)
      # https://docs.npmjs.com/policies/unpublish
      - run: npm unpublish @aws/codecatalyst-adk@${{ vars.UNPUBLISH_NPM_VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm unpublish @aws/codecatalyst-adk-core@${{ vars.UNPUBLISH_NPM_VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm unpublish @aws/codecatalyst-project@${{ vars.UNPUBLISH_NPM_VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #- run: npm unpublish @aws/codecatalyst-adk-model-parser@${{ vars.UNPUBLISH_NPM_VERSION }}
      # env:
      #    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #- run: npm unpublish @aws/codecatalyst-adk-utils@${{ vars.UNPUBLISH_NPM_VERSION }}
      #  env:
      #    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm unpublish @aws/codecatalyst-space@${{ vars.UNPUBLISH_NPM_VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm unpublish @aws/codecatalyst-run-summaries@${{ vars.UNPUBLISH_NPM_VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm unpublish @aws/codecatalyst-project@${{ vars.UNPUBLISH_NPM_VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
