# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - configs/.*\.ts
      - packages/.*/.*\.ts

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm set registry=https://npm.pkg.github.com --userconfig .npmrc    
      - run: npm set //npm.pkg.github.com/:always-auth=true --userconfig .npmrc
      - run: npm set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
      - run: npm install --global lerna@5.0.0 yarn@1.22.18
      - run: lerna --version
      - run: yarn --version
      - run: npm --version
      - run: lerna bootstrap
      - run: yarn run all
      - run: git config user.email "caws-aef-team-workflow@amazon.com"
      - run: git config user.name "ActionsDevKitRelease"      
      - run: git status && git add . && git commit -m "Release new version from GH Actions"
      - run: lerna version minor --no-push --yes
      - run: git status && git add CHANGELOG.md && git commit --amend --no-edit
      - run: git push origin HEAD:main
      - run: lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
