# This is a CI workflow that:
# - builds ADK packages
# - runs tests using jest test framework
# - runs api-ref scripts that generates API Reference docs to the docs/ folder
# - runs api-ref-pre-release scripts that generates API Reference docs to the pre-release-docs/ folder
# - runs generate-attributions that generates third party license attributions files
# - performs secrets scan using trufflesecurity/trufflehog GHA
# - performs vulnerabilities scan using returntocorp/semgrep GHA

name: adk-ci-test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Target branch of the pull request
          # Source https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
          ref: ${{ github.base_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm install --global lerna yarn #install global dependencies
      - run: yarn install #install and link depdendencies
      - run: ./build.sh #build
      - run: yarn run api-ref #test generate /docs
      - run: yarn run api-ref-pre-release #test generate /pre-release-docs
      - run: yarn run generate-attributions #test generate ./<package>/THIRD_PARTY_LICENSES
